application: agile-ratio-111
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: main.app
- url: /_ah/login_required
  script: do_openid_login.py

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
